version: "3"
services:
  app:
    build: .
    restart: on-failure
    ports:
      - "80:80"
    #volumes:
     # - /etc/letsencrypt/live/apis.tripease.my.id/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      #- /etc/letsencrypt/live/apis.tripease.my.id/privkey.pem:/etc/nginx/ssl/privkey.pem
