version: "3"
services:
  app:
    build: .
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/capstone.hanifz.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/capstone.hanifz.com/privkey.pem:/etc/nginx/ssl/privkey.pem
